"""
================================================================================
Pi Arena Lite - Master/display.py
The Numerical Audience Display for FRC 2026: REBUILT™

OVERALL PROJECT GOALS:
This script mimics the official FMS (Field Management System) experience. 
Drivers need to know their current standing relative to the 100/360 Fuel 
thresholds instantly. By using high-contrast numerical ratios instead of 
complex graphics, we ensure the data is readable from the opposite end of 
the practice field.

CORE FUNCTIONALITY:
This script acts as a 'Read-Only' observer. It polls the local state file 
generated by the Master Controller and renders the 'Progress-to-RP' logic 
in real-time. It handles the "Threshold Flip" once an alliance crosses 
the 100-ball mark.

================================================================================
Attribution:
- Core State Logic: Adapted from Cheesy Arena (BSD 3-Clause) by Team 254.
- Implementation: Developed as MIT-Licensed Open Source by Team 3476, 
  with architectural assistance from Google Gemini.
================================================================================
"""

import time
import json
import os

# --- DISPLAY CONSTANTS ---
STATE_FILE = "/tmp/field_state.json"
RP1 = 100
RP2 = 360

def render_fms_display():
    """
    Main loop that clears the terminal and draws the FMS-style interface.
    """
    while True:
        try:
            if not os.path.exists(STATE_FILE):
                print("Waiting for Master Controller...")
                time.sleep(1)
                continue

            with open(STATE_FILE, "r") as f:
                data = json.load(f)

            # --- RENDER LOGIC ---
            # Using ANSI clear to prevent flickering
            print("\033[H\033[J", end="") 
            
            print(f"=======================================================")
            print(f"  MATCH TIME: {data['time_left']:03d}s   |   STATE: {data['match_state']}")
            print(f"=======================================================")

            for a in ["red", "blue"]:
                fuel = data['scores'][a]
                
                # Determine Threshold & RP Status
                if fuel < RP1:
                    target = RP1
                    status = " [ ] ENERGIZING"
                elif fuel < RP2:
                    target = RP2
                    status = " [●] ENERGIZED"
                else:
                    target = fuel
                    status = " [✸] SUPERCHARGED"

                # Standard FMS "Numerator/Denominator" Layout
                # Example: "RED ALLIANCE:  142 / 360  [●] ENERGIZED"
                print(f"\n {a.upper():4} ALLIANCE:  {fuel:3} / {target:3}  {status}")
                
                # Auxiliary Data for Strategists
                zv = data['zero_value'][a]
                if zv > 0:
                    print(f"   (Zero-Value Scores: {zv})")

            print(f"\n=======================================================")
            
        except Exception as e:
            # Silently handle file-read collisions
            pass
        
        time.sleep(0.2) # 5Hz refresh is plenty for an audience display

if __name__ == "__main__":
    try:
        render_fms_display()
    except KeyboardInterrupt:
        print("\nDisplay closed.")
